name: Deploy React001 App

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install modules
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Build App
        run: npm run build